version: '2'
services:
  innovate-admin:
    image: hhufu/innovate-admin:latest
    privileged: true
    ports:
      - 8088:8080
    environment:
      - spring.profiles.active=prod
    restart: always
